# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Solo
email: info@solo-system.com

#description: Solo - a field recorder for bioacoustic research.  Outdoor, continuous, battery-powered, based on Raspberry-Pi, self-built, high-fidelity, configurable, user-servicable, cheap, modifiable, extensible, modular, open source.
description: Solo field recorder.


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.solo-system.org" # the base hostname & protocol for your site
#twitter_username: whatever
github_username:  solo-system


# Build settings
markdown: kramdown

# added jdmc2. -it didnt work.  Copied over, but didn't render.
#collections:
#  rpi:
#    output: true
#    permalink: /rpi/:path/
